import type { Locale } from "@/i18n/locales";

const copy = {
  skipToContent: { en: "Skip to content", ar: "تخطّ إلى المحتوى" },
  whatsapp: { en: "WhatsApp", ar: "واتساب" },
  email: { en: "Email", ar: "البريد" },
  phone: { en: "Phone", ar: "الهاتف" },
  location: { en: "Store location", ar: "موقع المعرض" },
  search: { en: "Search", ar: "بحث" },
  searchPlaceholder: { en: "Search products and services", ar: "ابحث في المنتجات والخدمات" },
  searchEmpty: { en: "No matches.", ar: "لا توجد نتائج." },
  requestQuote: { en: "Request a Quote", ar: "اطلب عرض سعر" },
  openMenu: { en: "Open menu", ar: "فتح القائمة" },
  closeMenu: { en: "Close menu", ar: "إغلاق القائمة" },
  primaryNav: { en: "Primary", ar: "الرئيسية" },
  submenu: { en: "Open submenu", ar: "فتح القائمة الفرعية" },
  getInTouch: { en: "Get in touch", ar: "تواصل معنا" },
  information: { en: "Information", ar: "معلومات" },
  usefulLinks: { en: "Useful links", ar: "روابط مفيدة" },
  aboutUs: { en: "About us", ar: "من نحن" },
  newsletterTitle: { en: "Print notes from Ghubairah", ar: "ملاحظات طباعة من غبيرة" },
  newsletterHint: {
    en: "Capacity, paper, and campaign dates. No cart, no list-dumping.",
    ar: "طاقة المطبعة والورق ومواعيد الحملات. بلا سلة وبلا رسائل فارغة.",
  },
  newsletterPlaceholder: { en: "Work email", ar: "البريد العملي" },
  newsletterSubmit: { en: "Subscribe", ar: "اشترك" },
  newsletterSuccess: { en: "You are on the list.", ar: "تم تسجيلكم." },
  newsletterError: { en: "Could not subscribe.", ar: "تعذّر الاشتراك." },
  copyright: { en: "All rights reserved.", ar: "جميع الحقوق محفوظة." },
  backToTop: { en: "Back to top", ar: "إلى الأعلى" },
  switchLanguage: { en: "العربية", ar: "English" },
  switchLanguageAria: { en: "Switch to Arabic", ar: "التبديل إلى الإنجليزية" },
  trustLine: {
    en: "Quote first · Bank transfer · Printed in Riyadh",
    ar: "عرض سعر أولاً · تحويل بنكي · طباعة في الرياض",
  },
  social: { en: "Social", ar: "التواصل" },
  getQuote: { en: "Get a Quote", ar: "اطلب عرض سعر" },
  sameDay: { en: "Same day", ar: "نفس اليوم" },
  fromPrice: { en: "From", ar: "من" },
  currency: { en: "SAR", ar: "ر.س" },
  share: { en: "Share", ar: "شارك" },
  shareWhatsapp: { en: "Share on WhatsApp", ar: "مشاركة عبر واتساب" },
  shareX: { en: "Share on X", ar: "مشاركة عبر X" },
  shareFacebook: { en: "Share on Facebook", ar: "مشاركة عبر فيسبوك" },
  shareLinkedin: { en: "Share on LinkedIn", ar: "مشاركة عبر لينكدإن" },
  shareEmail: { en: "Share by email", ar: "مشاركة بالبريد" },
  pagination: { en: "Pagination", ar: "ترقيم الصفحات" },
  previousPage: { en: "Previous page", ar: "الصفحة السابقة" },
  nextPage: { en: "Next page", ar: "الصفحة التالية" },
  pageOf: { en: "Page", ar: "صفحة" },
  searchHint: { en: "Press Ctrl+K to search", ar: "اضغط Ctrl+K للبحث" },
  searchGroupProduct: { en: "Products", ar: "المنتجات" },
  searchGroupService: { en: "Services", ar: "الخدمات" },
  searchGroupCategory: { en: "Categories", ar: "التصنيفات" },
  searchGroupPage: { en: "Pages", ar: "الصفحات" },
  searchGroupPost: { en: "Articles", ar: "المقالات" },
  searchGroupProject: { en: "Portfolio", ar: "أعمالنا" },
  lightbox: { en: "Image viewer", ar: "عارض الصور" },
  lightboxClose: { en: "Close", ar: "إغلاق" },
  lightboxPrev: { en: "Previous image", ar: "الصورة السابقة" },
  lightboxNext: { en: "Next image", ar: "الصورة التالية" },
  quoteName: { en: "Name", ar: "الاسم" },
  quoteEmail: { en: "Email", ar: "البريد" },
  quotePhone: { en: "Phone", ar: "الهاتف" },
  quoteCompany: { en: "Company", ar: "الشركة" },
  quoteService: { en: "Service", ar: "الخدمة" },
  quoteProduct: { en: "Product", ar: "المنتج" },
  quoteQuantity: { en: "Quantity", ar: "الكمية" },
  quoteMessage: { en: "Message", ar: "الرسالة" },
  quoteFile: { en: "Artwork or brief (PDF or image)", ar: "الملف أو الموجز (PDF أو صورة)" },
  quoteSubmit: { en: "Send quote request", ar: "إرسال طلب العرض" },
  quoteSuccess: { en: "Request received. We will reply from Ghubairah.", ar: "استلمنا الطلب وسنرد من غبيرة." },
  quoteWhatsapp: { en: "Continue on WhatsApp", ar: "متابعة عبر واتساب" },
  quoteSelect: { en: "Select…", ar: "اختر…" },
  quoteError: { en: "Could not send the request.", ar: "تعذّر إرسال الطلب." },
  whatsappFloat: { en: "Chat on WhatsApp", ar: "محادثة واتساب" },
} as const;

export type ChromeCopyKey = keyof typeof copy;

export function chromeText(locale: Locale, key: ChromeCopyKey): string {
  return copy[key][locale];
}
