import { prisma, tiptapDoc } from "./helpers";

type ServiceSeed = {
  slug: string;
  sortOrder: number;
  iconName: string;
  turnaroundTime: string;
  startingPrice: string;
  isFeatured: boolean;
  nameEn: string;
  nameAr: string;
  shortEn: string;
  shortAr: string;
  heroEn: string;
  heroAr: string;
  ctaEn: string;
  ctaAr: string;
};

const services: ServiceSeed[] = [
  {
    slug: "packaging-boxes",
    sortOrder: 0,
    iconName: "package",
    turnaroundTime: "4–8 days after proof",
    startingPrice: "350.00",
    isFeatured: true,
    nameEn: "Packaging boxes",
    nameAr: "علب التغليف",
    shortEn: "Mailers, cartons, and rigid boxes printed in Riyadh.",
    shortAr: "مغلفات وكرتون وعلب صلبة تُطبع في الرياض.",
    heroEn: "Professional packaging solutions in Riyadh",
    heroAr: "حلول تغليف احترافية في الرياض",
    ctaEn: "Request a packaging quote",
    ctaAr: "اطلب عرض سعر للتغليف",
  },
  {
    slug: "brochure-catalogue-printing-riyadh",
    sortOrder: 1,
    iconName: "book-open",
    turnaroundTime: "3–6 days after proof",
    startingPrice: "180.00",
    isFeatured: true,
    nameEn: "Brochure & catalogue printing",
    nameAr: "طباعة البروشور والكتالوج",
    shortEn: "Stitched catalogues and sales brochures.",
    shortAr: "كتالوجات مدبسة وبروشورات مبيعات.",
    heroEn: "Brochure and catalogue printing in Riyadh",
    heroAr: "طباعة البروشورات والكتالوجات في الرياض",
    ctaEn: "Send catalogue pages",
    ctaAr: "أرسل صفحات الكتالوج",
  },
  {
    slug: "book-cover-printing-riyadh",
    sortOrder: 2,
    iconName: "book",
    turnaroundTime: "5–10 days after proof",
    startingPrice: "220.00",
    isFeatured: false,
    nameEn: "Book cover printing",
    nameAr: "طباعة أغلفة الكتب",
    shortEn: "Covers and short-run publishing support.",
    shortAr: "أغلفة ودعم نشر بكميات قصيرة.",
    heroEn: "Book cover printing and publishing in Riyadh",
    heroAr: "طباعة أغلفة الكتب والنشر في الرياض",
    ctaEn: "Quote a cover",
    ctaAr: "سعّر غلافًا",
  },
  {
    slug: "banner-design-printing-riyadh",
    sortOrder: 3,
    iconName: "pen-tool",
    turnaroundTime: "1–3 days after proof",
    startingPrice: "120.00",
    isFeatured: false,
    nameEn: "Banner design & printing",
    nameAr: "تصميم وطباعة البنرات",
    shortEn: "Art and print for street and indoor banners.",
    shortAr: "تصميم وطباعة لبنرات الشارع والداخل.",
    heroEn: "Professional banner printing in Riyadh",
    heroAr: "طباعة بنرات احترافية في الرياض",
    ctaEn: "Start a banner",
    ctaAr: "ابدأ بنرًا",
  },
  {
    slug: "roller-banner-printing-riyadh",
    sortOrder: 4,
    iconName: "panel-top",
    turnaroundTime: "Same day – 48 hours",
    startingPrice: "180.00",
    isFeatured: true,
    nameEn: "Roller & pull-up banners",
    nameAr: "رول أب وسحب علوي",
    shortEn: "Retractable stands stocked in the city.",
    shortAr: "حاملات قابلة للطي متوفرة في المدينة.",
    heroEn: "Roller and pull-up banner printing in Riyadh",
    heroAr: "طباعة رول أب في الرياض",
    ctaEn: "Order a pull-up",
    ctaAr: "اطلب رول أب",
  },
  {
    slug: "poster-printing-riyadh",
    sortOrder: 5,
    iconName: "image",
    turnaroundTime: "Same day – 2 days",
    startingPrice: "40.00",
    isFeatured: false,
    nameEn: "Poster printing",
    nameAr: "طباعة البوسترات",
    shortEn: "Posters that hold colour under indoor lighting.",
    shortAr: "بوسترات تثبت اللون تحت إضاءة الداخل.",
    heroEn: "Posters that get noticed in Riyadh",
    heroAr: "بوسترات تُلاحظ في الرياض",
    ctaEn: "Print posters",
    ctaAr: "اطبع بوسترات",
  },
  {
    slug: "large-format-printing-in-riyadh",
    sortOrder: 6,
    iconName: "maximize",
    turnaroundTime: "1–4 days after proof",
    startingPrice: "90.00",
    isFeatured: true,
    nameEn: "Large format printing",
    nameAr: "طباعة القياس الكبير",
    shortEn: "Billboards, site boards, and wide vinyl.",
    shortAr: "لوحات طرق ولوحات مواقع وفينيل عريض.",
    heroEn: "Large format printing in Riyadh",
    heroAr: "طباعة القياس الكبير في الرياض",
    ctaEn: "Quote large format",
    ctaAr: "سعّر قياسًا كبيرًا",
  },
  {
    slug: "brochure-printing-riyadh",
    sortOrder: 7,
    iconName: "files",
    turnaroundTime: "2–4 days after proof",
    startingPrice: "95.00",
    isFeatured: false,
    nameEn: "Brochure printing",
    nameAr: "طباعة البروشور",
    shortEn: "Folded brochures for sales teams.",
    shortAr: "بروشورات مطوية لفرق المبيعات.",
    heroEn: "Brochure printing done right in Riyadh",
    heroAr: "طباعة بروشور صحيحة في الرياض",
    ctaEn: "Quote brochures",
    ctaAr: "سعّر بروشورات",
  },
  {
    slug: "same-day-printing-riyadh",
    sortOrder: 8,
    iconName: "zap",
    turnaroundTime: "Same day (Riyadh)",
    startingPrice: "75.00",
    isFeatured: true,
    nameEn: "Same-day printing",
    nameAr: "طباعة في نفس اليوم",
    shortEn: "Urgent cards, flyers, and selected banners.",
    shortAr: "بطاقات وفلايرات وبنرات مختارة بشكل عاجل.",
    heroEn: "Same-day printing in Riyadh",
    heroAr: "طباعة في نفس اليوم في الرياض",
    ctaEn: "Ask for today",
    ctaAr: "اسأل عن اليوم",
  },
  {
    slug: "flyer-printing-riyadh",
    sortOrder: 9,
    iconName: "file-text",
    turnaroundTime: "Same day – 3 days",
    startingPrice: "85.00",
    isFeatured: false,
    nameEn: "Flyer printing",
    nameAr: "طباعة الفلايرات",
    shortEn: "High-volume flyers with a written date.",
    shortAr: "فلايرات بكميات مع موعد مكتوب.",
    heroEn: "Flyer printing that gets results",
    heroAr: "فلايرات تحقق نتيجة",
    ctaEn: "Quote flyers",
    ctaAr: "سعّر فلايرات",
  },
  {
    slug: "professional-business-card-printing-riyadh-riyadh-prints",
    sortOrder: 10,
    iconName: "id-card",
    turnaroundTime: "Same day – 48 hours",
    startingPrice: "60.00",
    isFeatured: true,
    nameEn: "Business card printing",
    nameAr: "طباعة بطاقات الأعمال",
    shortEn: "Same-day cards; free layout help on request.",
    shortAr: "بطاقات في نفس اليوم مع مساعدة تصميم عند الطلب.",
    heroEn: "Professional business card printing in Riyadh",
    heroAr: "طباعة بطاقات أعمال احترافية في الرياض",
    ctaEn: "Request card quote",
    ctaAr: "اطلب عرض البطاقات",
  },
  {
    slug: "banner-printing-riyadh",
    sortOrder: 11,
    iconName: "flag",
    turnaroundTime: "Same day – 3 days",
    startingPrice: "110.00",
    isFeatured: false,
    nameEn: "Banner printing",
    nameAr: "طباعة البنرات",
    shortEn: "Street and indoor banners with hardware options.",
    shortAr: "بنرات شارع وداخل مع خيارات تركيب.",
    heroEn: "Banner printing in Riyadh",
    heroAr: "طباعة بنرات في الرياض",
    ctaEn: "Call for banners",
    ctaAr: "اتصل للبنرات",
  },
];

export async function seedServices() {
  for (const item of services) {
    const service = await prisma.service.upsert({
      where: { slug: item.slug },
      create: {
        slug: item.slug,
        iconName: item.iconName,
        sortOrder: item.sortOrder,
        isFeatured: item.isFeatured,
        turnaroundTime: item.turnaroundTime,
        startingPrice: item.startingPrice,
        status: "PUBLISHED",
        publishedAt: new Date(),
        showInSitemap: true,
        legacyPath: `/services/${item.slug}/`,
      },
      update: {
        iconName: item.iconName,
        sortOrder: item.sortOrder,
        isFeatured: item.isFeatured,
        turnaroundTime: item.turnaroundTime,
        startingPrice: item.startingPrice,
        status: "PUBLISHED",
        publishedAt: new Date(),
        legacyPath: `/services/${item.slug}/`,
      },
    });

    await prisma.serviceTranslation.upsert({
      where: { serviceId_locale: { serviceId: service.id, locale: "EN" } },
      create: {
        serviceId: service.id,
        locale: "EN",
        name: item.nameEn,
        slug: item.slug,
        shortDescription: item.shortEn,
        longDescription: tiptapDoc(item.shortEn, item.heroEn),
        benefits: [
          "Printed in Riyadh",
          "Digital proof before production",
          "Quote on WhatsApp",
        ],
        processSteps: [
          { title: "Send files", body: "PDF, AI, or PNG with bleed." },
          { title: "Approve proof", body: "We do not print until you sign off." },
          { title: "Collect or deliver", body: "Ghubairah pickup or KSA shipping." },
        ],
        heroHeading: item.heroEn,
        heroSubheading: item.shortEn,
        ctaLabel: item.ctaEn,
        metaTitle: item.heroEn,
        metaDescription: item.shortEn,
        focusKeyword: item.nameEn.toLowerCase(),
      },
      update: {
        name: item.nameEn,
        slug: item.slug,
        shortDescription: item.shortEn,
        longDescription: tiptapDoc(item.shortEn, item.heroEn),
        heroHeading: item.heroEn,
        ctaLabel: item.ctaEn,
        metaTitle: item.heroEn,
        metaDescription: item.shortEn,
      },
    });

    await prisma.serviceTranslation.upsert({
      where: { serviceId_locale: { serviceId: service.id, locale: "AR" } },
      create: {
        serviceId: service.id,
        locale: "AR",
        name: item.nameAr,
        slug: item.slug,
        shortDescription: item.shortAr,
        longDescription: tiptapDoc(item.shortAr, item.heroAr),
        benefits: ["طباعة في الرياض", "بروفة قبل التشغيل", "عرض سعر عبر واتساب"],
        processSteps: [
          { title: "أرسل الملفات", body: "PDF أو AI أو PNG مع هدر." },
          { title: "اعتمد البروفة", body: "لا نطبع قبل اعتمادكم." },
          { title: "استلام أو توصيل", body: "من غبيرة أو شحن داخل المملكة." },
        ],
        heroHeading: item.heroAr,
        heroSubheading: item.shortAr,
        ctaLabel: item.ctaAr,
        metaTitle: item.heroAr,
        metaDescription: item.shortAr,
        focusKeyword: item.nameAr,
      },
      update: {
        name: item.nameAr,
        slug: item.slug,
        shortDescription: item.shortAr,
        longDescription: tiptapDoc(item.shortAr, item.heroAr),
        heroHeading: item.heroAr,
        ctaLabel: item.ctaAr,
        metaTitle: item.heroAr,
        metaDescription: item.shortAr,
      },
    });
  }
}
